name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      -main
jobs:
  build:
    runs-on: ubuntu-latest
  steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Build app with Maven
      run: mvn clean package -DskipTests

    - name: Setup environment variables
      run: echo "MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}" >> $GITHUB_ENV
      env:
        MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD}}
        SPRING_ DATASOURCE _USERNAME: ${{ secrets. SPRING_ DATASOURCE _USERNAME }}
        SPRING DATASOURCE_PASSWORD: ${{ secrets. SPRING DATASOURCE_PASSWORD }}
